-- CharacterArc Supabase setup
-- Run this once in Supabase SQL Editor.

begin;

create table if not exists public.daily_actions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  label text not null,
  amount integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.daily_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  total_xp integer not null default 0,
  traits jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_progress_user_date_key unique (user_id, date)
);

create table if not exists public.daily_reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  content text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint daily_reflections_user_date_key unique (user_id, date)
);

create index if not exists daily_actions_user_date_idx
  on public.daily_actions (user_id, date, id);

create index if not exists daily_progress_user_date_idx
  on public.daily_progress (user_id, date);

create index if not exists daily_reflections_user_date_idx
  on public.daily_reflections (user_id, date);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_daily_progress_updated_at on public.daily_progress;
create trigger set_daily_progress_updated_at
before update on public.daily_progress
for each row
execute function public.set_updated_at();

drop trigger if exists set_daily_reflections_updated_at on public.daily_reflections;
create trigger set_daily_reflections_updated_at
before update on public.daily_reflections
for each row
execute function public.set_updated_at();

alter table public.daily_actions enable row level security;
alter table public.daily_progress enable row level security;
alter table public.daily_reflections enable row level security;

-- Keep anonymous browser requests out of the tracker tables. Signed-in users
-- receive table permissions below, then RLS limits them to their own rows.
revoke all on table public.daily_actions from anon;
revoke all on table public.daily_progress from anon;
revoke all on table public.daily_reflections from anon;

drop policy if exists "Users can manage their own daily actions" on public.daily_actions;
drop policy if exists "Users can read their own daily actions" on public.daily_actions;
drop policy if exists "Users can insert their own daily actions" on public.daily_actions;
drop policy if exists "Users can update their own daily actions" on public.daily_actions;
drop policy if exists "Users can delete their own daily actions" on public.daily_actions;

create policy "Users can read their own daily actions"
on public.daily_actions
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own daily actions"
on public.daily_actions
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own daily actions"
on public.daily_actions
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own daily actions"
on public.daily_actions
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can manage their own daily progress" on public.daily_progress;
drop policy if exists "Users can read their own daily progress" on public.daily_progress;
drop policy if exists "Users can insert their own daily progress" on public.daily_progress;
drop policy if exists "Users can update their own daily progress" on public.daily_progress;
drop policy if exists "Users can delete their own daily progress" on public.daily_progress;

create policy "Users can read their own daily progress"
on public.daily_progress
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own daily progress"
on public.daily_progress
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own daily progress"
on public.daily_progress
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own daily progress"
on public.daily_progress
for delete
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can manage their own daily reflections" on public.daily_reflections;
drop policy if exists "Users can read their own daily reflections" on public.daily_reflections;
drop policy if exists "Users can insert their own daily reflections" on public.daily_reflections;
drop policy if exists "Users can update their own daily reflections" on public.daily_reflections;
drop policy if exists "Users can delete their own daily reflections" on public.daily_reflections;

create policy "Users can read their own daily reflections"
on public.daily_reflections
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can insert their own daily reflections"
on public.daily_reflections
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own daily reflections"
on public.daily_reflections
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own daily reflections"
on public.daily_reflections
for delete
to authenticated
using ((select auth.uid()) = user_id);

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.daily_actions to authenticated;
grant select, insert, update, delete on public.daily_progress to authenticated;
grant select, insert, update, delete on public.daily_reflections to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- The account-deletion Route Handler uses a service-role Supabase client.
-- Service-role requests bypass RLS, but explicit table grants keep that path
-- working even if the project defaults were tightened.
grant usage on schema public to service_role;
grant select, insert, update, delete on public.daily_actions to service_role;
grant select, insert, update, delete on public.daily_progress to service_role;
grant select, insert, update, delete on public.daily_reflections to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;

-- The SQL Editor result should list all 12 authenticated policies with RLS on.
select
  policies.tablename,
  policies.policyname,
  policies.cmd,
  policies.roles,
  tables.rowsecurity as rls_enabled
from pg_policies as policies
join pg_tables as tables
  on tables.schemaname = policies.schemaname
 and tables.tablename = policies.tablename
where policies.schemaname = 'public'
  and policies.tablename in (
    'daily_actions',
    'daily_progress',
    'daily_reflections'
  )
order by policies.tablename, policies.cmd;
